### PR TITLE
Fix Date constructor arguments

### PR DESCRIPTION
**Pull request by feimosi**
The argument month is 0-based. This means that January = 0 and December = 11.

### CODE REVIEW

**Comment by rubencodes** [comment]
Great catch! We'd probably also have to fix this line here: https://github.com/rubencodes/recal/blob/e161948390ea3ab919d41e39be41bffb85268f20/src/lib/CalendarHeader.jsx#L18 which uses the function in its current state. If you could make that change,  I'll happily merge this.

**Comment by feimosi** [comment]
That's actually working fine because you're adding +1 in the constructor here:
https://github.com/rubencodes/recal/blob/e161948390ea3ab919d41e39be41bffb85268f20/src/lib/index.jsx#L24
Therefore we either have to change both places or leave it as it is.

**Comment by rubencodes** [comment]
Ah, understood. I'll merge this in and fix in both places for consistency down the line. Thanks!

**Comment by rubencodes** [comment]
Actually, before I do that; just ran a quick test.

```
[...Array(12)].map((_, i) => {
    let baseDate = new Date(Date.UTC(2017, i + 1, 1));
 	 
    return baseDate.toLocaleDateString('en-US', { month: 'long' });
});
```

(e.g. the current code) seems to yield this array: `["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]`.

Removing the "+ 1" (your edit) results in this same array, but starting with December. 

I believe this has to do with the Date.UTC initializer, which I'm not sure is necessary—removing both the "Date.UTC" initializer and "+ 1" seems to give me the same Jan-Dec array.

**Comment by feimosi** [comment]
That's weird, I'm getting the opposite. Removing the "+ 1" results in starting with January, which makes sense as months are 0-based in JS. Maybe `Date.UTC` is not consistent in this matter? 
I guess we don't need it anyway, unless we're working on time units (hours etc.)

**Comment by rubencodes** [comment]
How interesting! I bet it's a timezone issue! So to be sure, does this return Jan-Dec on your end?

```
[...Array(12)].map((_, i) => {
    let baseDate = new Date(2017, i, 1);
 	 
    return baseDate.toLocaleDateString('en-US', { month: 'long' });
});
```

**Comment by feimosi** [comment]
Yes, confirmed:

image

Hmm if it's a timezone issue, then changing the day should give us the answer (as the 1st in Japan can be the 30th in the US). Could you try running the following?

```
new Date(2017, i, 2);
```

**Comment by rubencodes** [comment]
screen shot 2018-05-17 at 9 02 42 am

`new Date(2017, i, 2)` gave me the same Jan-Dec result, presumably because the month is still the same. Is that what you were looking for?

**Comment by feimosi** [comment]
Sorry, my bad, I meant with `Date.UTC`. Actually I could do the experiment myself. The first result is for the UTC+2 and the second one for UTC-10. 

image

Here's with `new Date(Date.UTC(2017, i, 2))`

image

Everything's clear now, anyway, we probably don't need `Date.UTC` at all, right?

**Comment by rubencodes** [comment]
Yeah, since the timezone doesn't matter, seems like Date.UTC is overkill. Can probably update to `new Date(2017, i, 1)`.

**Comment by feimosi** [comment]
I've updated the PR.

**Pull request merged**
